text = input('digite algo:')

tipo = type(text)
somente_espaco = text.isspace()
numerico = text.isnumeric()
alfabetico = text.isalpha()
alfanumerico = text.isalnum()
maiusculo = text.isupper()
minusculo = text.islower()
captalizado = text.istitle()

print('tipo:', tipo)
print('só espaço:', somente_espaco)
print('numerico:', numerico)
print('alfabetico:', alfabetico)
print('alfanumerico:', alfanumerico)
print('maiusculo:', maiusculo)
print('minusculo:', minusculo)
print('captalizado:', captalizado)
